package com.lox.token;

public enum Type {
    NUMBER, STRING, BOOLEAN, NULL, IDENTIFIER,
    
    VAR, FUN, CONST, RETURN, THROW,
    IF, ELSE, WHILE, BREAK, CONTINUE,
    
    PLUS, MINUS, STAR, SLASH, PERCENT, QUESTION, QUESTION_QUESTION,
    PLUS_PLUS, MINUS_MINUS,
    EQ, EQ_EQ, NOT, NOT_EQ, LT, GT, LTE, GTE,
    AND, AND_AND, OR, OR_OR,
    
    PLUS_EQ, MINUS_EQ, STAR_EQ, SLASH_EQ, PERCENT_EQ,
    AND_EQ, OR_EQ,
    
    ARROW, ELLIPSIS,
    
    LPAREN, RPAREN, LBRACE, RBRACE,
    LBRACKET, RBRACKET, COMMA, DOT, SEMICOLON, COLON,
    
    EOF
}